Fix `zfs send` from a bookmark
We can't send all intermediary snapshots from a bookmark, because

  Error: multiple snapshots cannot be sent from a bookmark.

So instead of one step, let's make two steps:

  1. from a bookmark to next snapshot

  2. from next snapshot to last snapshot, including all intermediary snapshots.